//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Funkmap.Auth.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery code.
        /// </summary>
        public static string PasswordRecovery_Code {
            get {
                return ResourceManager.GetString("PasswordRecovery_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each new user improves and develops the service, making it more extensive. We appreciate you and your choice..
        /// </summary>
        public static string Registration_Appreciate {
            get {
                return ResourceManager.GetString("Registration_Appreciate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation.
        /// </summary>
        public static string Registration_Confirmation {
            get {
                return ResourceManager.GetString("Registration_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation code.
        /// </summary>
        public static string Registration_ConfirmationCode {
            get {
                return ResourceManager.GetString("Registration_ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for joinin to Band Map.
        /// </summary>
        public static string Registration_Gratitude {
            get {
                return ResourceManager.GetString("Registration_Gratitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Registration_Greeting {
            get {
                return ResourceManager.GetString("Registration_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the largest service for looking for musicians and everything that connects them.
        /// </summary>
        public static string Registration_Welcome {
            get {
                return ResourceManager.GetString("Registration_Welcome", resourceCulture);
            }
        }
    }
}
